/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * NoteApp API
 * A simple note app with folders and user support.
 * OpenAPI spec version: 1.0.0
 */
import type { BodyLoginGrantType } from "./bodyLoginGrantType";
import type { BodyLoginClientId } from "./bodyLoginClientId";
import type { BodyLoginClientSecret } from "./bodyLoginClientSecret";

export interface BodyLogin {
  grant_type?: BodyLoginGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginClientId;
  client_secret?: BodyLoginClientSecret;
}
