/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * NoteApp API
 * A simple note app with folders and user support.
 * OpenAPI spec version: 1.0.0
 */
import type { NoteUpdateTitle } from "./noteUpdateTitle";
import type { NoteUpdateContent } from "./noteUpdateContent";
import type { NoteUpdateFolderId } from "./noteUpdateFolderId";
import type { NoteUpdateIsStarred } from "./noteUpdateIsStarred";

export interface NoteUpdate {
  title?: NoteUpdateTitle;
  content?: NoteUpdateContent;
  folder_id?: NoteUpdateFolderId;
  is_starred?: NoteUpdateIsStarred;
}
