/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * NoteApp API
 * A simple note app with folders and user support.
 * OpenAPI spec version: 1.0.0
 */
import type { NoteCreateContent } from "./noteCreateContent";
import type { NoteCreateFolderId } from "./noteCreateFolderId";

export interface NoteCreate {
  /** @maxLength 50 */
  title: string;
  content?: NoteCreateContent;
  folder_id?: NoteCreateFolderId;
  is_starred?: boolean;
}
