/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * NoteApp API
 * A simple note app with folders and user support.
 * OpenAPI spec version: 1.0.0
 */

export interface UserCreate {
  /** @maxLength 40 */
  first_name: string;
  /** @maxLength 40 */
  last_name: string;
  email: string;
  is_active?: boolean;
  /**
   * @minLength 8
   * @maxLength 40
   */
  password: string;
}
